/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dis.practicadis.interfaz.vistacontrolador.registrarempleado;

import dis.practicadis.dominio.modelo.Destino;
import dis.practicadis.dominio.modelo.Direccion;
import dis.practicadis.dominio.modelo.Empleado;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaRegistrarEmpleado extends javax.swing.JFrame {

    private ControladorVistaRegistrarEmpleado controlador;

    /**
     * Creates new form VistaRegistrarEmpleado
     */
    public VistaRegistrarEmpleado() {
        initComponents();
        controlador = new ControladorVistaRegistrarEmpleado(this);
        setResizable(false);
        jPanel_nif.setVisible(true);
        jPanel_aceptardatos.setVisible(false);
        jPanel_datos.setVisible(true);
        jPanel_aceptacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_superior = new javax.swing.JPanel();
        jSeparator = new javax.swing.JSeparator();
        jLabel_manzana = new javax.swing.JLabel();
        jLabel_blue = new javax.swing.JLabel();
        jPanel_inferior = new javax.swing.JPanel();
        jPanel_aceptacion = new javax.swing.JPanel();
        jLabel_registroempleado = new javax.swing.JLabel();
        jLabel_datos = new javax.swing.JLabel();
        jLabel_nombreyapellidos = new javax.swing.JLabel();
        jLabel_contacto = new javax.swing.JLabel();
        jLabel_direccioncompleta = new javax.swing.JLabel();
        jLabel_ibanmostrar = new javax.swing.JLabel();
        jLabel_seguridadsocialmostrar = new javax.swing.JLabel();
        jLabel_rol = new javax.swing.JLabel();
        jTextField_rol = new javax.swing.JTextField();
        jLabel_destino = new javax.swing.JLabel();
        jTextField_destino = new javax.swing.JTextField();
        jButton_aceptarfinal = new javax.swing.JButton();
        jButton_cancelarfinal = new javax.swing.JButton();
        jPanel_datos = new javax.swing.JPanel();
        jLabel_registro = new javax.swing.JLabel();
        jLabel_nif = new javax.swing.JLabel();
        jTextField_nif = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_apellidos = new javax.swing.JLabel();
        jTextField_apellidos = new javax.swing.JTextField();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel_iban = new javax.swing.JLabel();
        jTextField_iban = new javax.swing.JTextField();
        jLabel_seguridadsocial = new javax.swing.JLabel();
        jTextField_seguridadsocial = new javax.swing.JTextField();
        jSeparator_datos = new javax.swing.JSeparator();
        jLabel_calle = new javax.swing.JLabel();
        jTextField_calle = new javax.swing.JTextField();
        jLabel_numero = new javax.swing.JLabel();
        jTextField_numero = new javax.swing.JTextField();
        jLabel_otros = new javax.swing.JLabel();
        jTextField_otros = new javax.swing.JTextField();
        jLabel_codigopostal = new javax.swing.JLabel();
        jTextField_codigopostal = new javax.swing.JTextField();
        jLabel_localidad = new javax.swing.JLabel();
        jTextField_localidad = new javax.swing.JTextField();
        jLabel_provincia = new javax.swing.JLabel();
        jTextField_provincia = new javax.swing.JTextField();
        jPanel_botones = new javax.swing.JPanel();
        jPanel_nif = new javax.swing.JPanel();
        jButton_nif = new javax.swing.JButton();
        jButton_cancelarcompleto = new javax.swing.JButton();
        jPanel_aceptardatos = new javax.swing.JPanel();
        jButton_cancelardatos = new javax.swing.JButton();
        jButton_aceptardatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator.setBackground(new java.awt.Color(50, 85, 150));

        jLabel_manzana.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_manzana.setForeground(new java.awt.Color(50, 85, 150));
        jLabel_manzana.setText("Manzana");

        jLabel_blue.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_blue.setForeground(new java.awt.Color(195, 195, 195));
        jLabel_blue.setText("BLUE");

        javax.swing.GroupLayout jPanel_superiorLayout = new javax.swing.GroupLayout(jPanel_superior);
        jPanel_superior.setLayout(jPanel_superiorLayout);
        jPanel_superiorLayout.setHorizontalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_blue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_manzana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_superiorLayout.setVerticalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_blue)
                    .addComponent(jLabel_manzana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_inferior.setLayout(new java.awt.CardLayout());

        jLabel_registroempleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_registroempleado.setText("Registro de nuevo empleado");

        jLabel_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_datos.setText("Datos de empleado:");

        jLabel_nombreyapellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombreyapellidos.setText("temp");

        jLabel_contacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_contacto.setText("temp");

        jLabel_direccioncompleta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_direccioncompleta.setText("temp");

        jLabel_ibanmostrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_ibanmostrar.setText("temp");

        jLabel_seguridadsocialmostrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_seguridadsocialmostrar.setText("temp");

        jLabel_rol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_rol.setText("Rol de Empleado:");

        jLabel_destino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_destino.setText("ID de Destino:");

        jButton_aceptarfinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_aceptarfinal.setText("Aceptar");
        jButton_aceptarfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarfinalActionPerformed(evt);
            }
        });

        jButton_cancelarfinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_cancelarfinal.setText("Cancelar");
        jButton_cancelarfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarfinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_aceptacionLayout = new javax.swing.GroupLayout(jPanel_aceptacion);
        jPanel_aceptacion.setLayout(jPanel_aceptacionLayout);
        jPanel_aceptacionLayout.setHorizontalGroup(
            jPanel_aceptacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aceptacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_aceptacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_aceptacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_cancelarfinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_aceptarfinal))
                    .addGroup(jPanel_aceptacionLayout.createSequentialGroup()
                        .addGroup(jPanel_aceptacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_registroempleado)
                            .addComponent(jLabel_datos)
                            .addComponent(jLabel_nombreyapellidos)
                            .addComponent(jLabel_contacto)
                            .addComponent(jLabel_direccioncompleta)
                            .addComponent(jLabel_ibanmostrar)
                            .addGroup(jPanel_aceptacionLayout.createSequentialGroup()
                                .addComponent(jLabel_rol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_destino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_seguridadsocialmostrar))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_aceptacionLayout.setVerticalGroup(
            jPanel_aceptacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aceptacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_registroempleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_datos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_nombreyapellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_contacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_direccioncompleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ibanmostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_seguridadsocialmostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_aceptacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_rol)
                    .addComponent(jTextField_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_destino)
                    .addComponent(jTextField_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel_aceptacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aceptarfinal)
                    .addComponent(jButton_cancelarfinal))
                .addContainerGap())
        );

        jPanel_inferior.add(jPanel_aceptacion, "card2");

        jLabel_registro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_registro.setText("Registro de nuevo empleado");

        jLabel_nif.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nif.setText("nif:");

        jLabel_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombre.setText("Nombre:");
        jLabel_nombre.setEnabled(false);

        jTextField_nombre.setEnabled(false);

        jLabel_apellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_apellidos.setText("Apellidos:");
        jLabel_apellidos.setEnabled(false);

        jTextField_apellidos.setEnabled(false);

        jLabel_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_telefono.setText("Teléfono:");
        jLabel_telefono.setEnabled(false);

        jTextField_telefono.setEnabled(false);

        jLabel_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_email.setText("e-mail:");
        jLabel_email.setEnabled(false);

        jTextField_email.setEnabled(false);

        jLabel_iban.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_iban.setText("IBAN:");
        jLabel_iban.setEnabled(false);

        jTextField_iban.setEnabled(false);

        jLabel_seguridadsocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_seguridadsocial.setText("Seg. Social:");
        jLabel_seguridadsocial.setEnabled(false);

        jTextField_seguridadsocial.setEnabled(false);

        jSeparator_datos.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator_datos.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_calle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_calle.setText("Calle:");
        jLabel_calle.setEnabled(false);

        jTextField_calle.setEnabled(false);

        jLabel_numero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_numero.setText("Numero:");
        jLabel_numero.setEnabled(false);

        jTextField_numero.setEnabled(false);

        jLabel_otros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_otros.setText("Otros:");
        jLabel_otros.setEnabled(false);

        jTextField_otros.setEnabled(false);
        jTextField_otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_otrosActionPerformed(evt);
            }
        });

        jLabel_codigopostal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_codigopostal.setText("Cod. Postal:");
        jLabel_codigopostal.setEnabled(false);

        jTextField_codigopostal.setEnabled(false);

        jLabel_localidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_localidad.setText("Localidad:");
        jLabel_localidad.setEnabled(false);

        jTextField_localidad.setEnabled(false);

        jLabel_provincia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_provincia.setText("Provincia:");
        jLabel_provincia.setEnabled(false);

        jTextField_provincia.setEnabled(false);
        jTextField_provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_provinciaActionPerformed(evt);
            }
        });

        jPanel_botones.setLayout(new java.awt.CardLayout());

        jButton_nif.setText("OK");
        jButton_nif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nifActionPerformed(evt);
            }
        });

        jButton_cancelarcompleto.setText("Cancelar");
        jButton_cancelarcompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarcompletoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_nifLayout = new javax.swing.GroupLayout(jPanel_nif);
        jPanel_nif.setLayout(jPanel_nifLayout);
        jPanel_nifLayout.setHorizontalGroup(
            jPanel_nifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nifLayout.createSequentialGroup()
                .addComponent(jButton_nif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_cancelarcompleto)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        jPanel_nifLayout.setVerticalGroup(
            jPanel_nifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nifLayout.createSequentialGroup()
                .addGroup(jPanel_nifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nif)
                    .addComponent(jButton_cancelarcompleto))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel_botones.add(jPanel_nif, "card2");

        jButton_cancelardatos.setText("Cancelar");
        jButton_cancelardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelardatosActionPerformed(evt);
            }
        });

        jButton_aceptardatos.setText("OK");
        jButton_aceptardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptardatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_aceptardatosLayout = new javax.swing.GroupLayout(jPanel_aceptardatos);
        jPanel_aceptardatos.setLayout(jPanel_aceptardatosLayout);
        jPanel_aceptardatosLayout.setHorizontalGroup(
            jPanel_aceptardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aceptardatosLayout.createSequentialGroup()
                .addComponent(jButton_cancelardatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_aceptardatos)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        jPanel_aceptardatosLayout.setVerticalGroup(
            jPanel_aceptardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_aceptardatosLayout.createSequentialGroup()
                .addGroup(jPanel_aceptardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cancelardatos)
                    .addComponent(jButton_aceptardatos))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel_botones.add(jPanel_aceptardatos, "card3");

        javax.swing.GroupLayout jPanel_datosLayout = new javax.swing.GroupLayout(jPanel_datos);
        jPanel_datos.setLayout(jPanel_datosLayout);
        jPanel_datosLayout.setHorizontalGroup(
            jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_seguridadsocial)
                                    .addComponent(jLabel_email)
                                    .addComponent(jLabel_iban))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_email)
                                    .addComponent(jTextField_iban)
                                    .addComponent(jTextField_seguridadsocial)))
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addComponent(jLabel_telefono)
                                .addGap(20, 20, 20)
                                .addComponent(jTextField_telefono))
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_apellidos)
                                    .addComponent(jLabel_nombre))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_nombre)
                                    .addComponent(jTextField_apellidos))))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_numero)
                            .addComponent(jLabel_otros)
                            .addComponent(jLabel_calle)
                            .addComponent(jLabel_codigopostal)
                            .addComponent(jLabel_localidad)
                            .addComponent(jLabel_provincia))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_codigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_otros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTextField_localidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_provincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_registro)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addComponent(jLabel_nif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_datosLayout.setVerticalGroup(
            jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_nif)
                        .addComponent(jTextField_nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addComponent(jSeparator_datos, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel_datosLayout.createSequentialGroup()
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_nombre)
                                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_apellidos)
                                    .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_telefono)))
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_calle)
                                    .addComponent(jTextField_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_numero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_otros))))
                        .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_codigopostal)
                                    .addComponent(jTextField_codigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_localidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_provincia)))
                            .addGroup(jPanel_datosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_iban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_iban))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_seguridadsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_seguridadsocial))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel_inferior.add(jPanel_datos, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nifActionPerformed

        if (jTextField_nif.getText().isEmpty()) {
            errorControlador("El NIF esta vacío");
        } else {
            controlador.procesarEventoNif();
        }
    }//GEN-LAST:event_jButton_nifActionPerformed

    private void jTextField_otrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_otrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_otrosActionPerformed

    private void jTextField_provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_provinciaActionPerformed

    private void jButton_cancelardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelardatosActionPerformed
        controlador.cancelarNif();
    }//GEN-LAST:event_jButton_cancelardatosActionPerformed

    private void jButton_aceptardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptardatosActionPerformed

        if (this.getNombreValue().isEmpty()) {
            errorControlador("El campo nombre esta vacio.");
        } else if (this.getApellidosValue().isEmpty()) {
            errorControlador("El campo apellidos esta vacio.");
        } else if (this.getNifValue().isEmpty()) {
            errorControlador("El campo nif esta vacio.");
        } else if (this.getTelefonoValue().isEmpty()) {
            errorControlador("El campo telefono esta vacio.");
        } else if (this.getEmailValue().isEmpty()) {
            errorControlador("El campo email esta vacio.");
        } else if (this.getSeguridadSocialValue().isEmpty()) {
            errorControlador("El campo numero seguridad social esta vacio.");
        } else if (this.getIBANValue().isEmpty()) {
            errorControlador("El campo iban esta vacio.");
        } else if (this.getCalleValue().isEmpty()) {
            errorControlador("El campo calle esta vacio.");
        } else if (this.getNumeroValue().isEmpty()) {
            errorControlador("El campo numero esta vacio.");
        } else if (this.getCodigoPostalValue().isEmpty()) {
            errorControlador("El campo codigo postal esta vacio.");
        } else if (this.getLocalidadValue().isEmpty()) {
            errorControlador("El campo localidad esta vacio.");
        } else if (this.getProvinciaValue().isEmpty()) {
            errorControlador("El campo provincia esta vacio.");
        } else {
            if (this.getNombreValue().matches("[A-Za-z]{1,30}")) {
                if (this.getApellidosValue().matches("[A-Za-z ]{1,30}")) {
                    if (this.getTelefonoValue().matches("[0-9]{1,30}")) {
                        if (this.getEmailValue()
                                .matches("[a-zA-Z0-9._]+@[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*")
                                && this.getNombreValue().length() <= 100) {
                            if (this.getIBANValue().matches("[0-9]{24}")) {
                                if (this.getSeguridadSocialValue().matches("[0-9]{12}")) {
                                    controlador.procesarEventoDatos();
                                } else {
                                    errorControlador("El numero de la seguridad social es invalido.");
                                    this.jTextField_seguridadsocial.setText("");
                                }
                            } else {
                                errorControlador("El IBAN es invalido.");
                                this.jTextField_iban.setText("");
                            }
                        } else {
                            errorControlador("El e-mail es invalido.");
                            this.jTextField_email.setText("");
                        }
                    } else {
                        errorControlador("El telefono es invalido.");
                        this.jTextField_telefono.setText("");
                    }
                } else {
                    errorControlador("Los apellidos son invalidos.");
                    this.jTextField_apellidos.setText("");
                }
            } else {
                errorControlador("El nombre es invalido.");
                this.jTextField_nombre.setText("");
            }
        }


    }//GEN-LAST:event_jButton_aceptardatosActionPerformed

    private void jButton_aceptarfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarfinalActionPerformed
        if(this.jTextField_rol.getText().isEmpty()){
            errorControlador("El campo rol esta vacio.");
        } else if(this.jTextField_destino.getText().isEmpty()){
            errorControlador("El campo destino esta vacio.");
        } else{
            if (this.getDestinoValue().matches("[0-9]*")) {
                controlador.procesarEventoRolYDestino();
            } else {
                errorControlador("La id de destino es invalida.");
                cancelarRolYDestino();
            } 
        }
    }//GEN-LAST:event_jButton_aceptarfinalActionPerformed

    private void jButton_cancelarfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarfinalActionPerformed
        controlador.cancelarDatos();
    }//GEN-LAST:event_jButton_cancelarfinalActionPerformed

    private void jButton_cancelarcompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarcompletoActionPerformed
        controlador.cancelarCompleto();
        
    }//GEN-LAST:event_jButton_cancelarcompletoActionPerformed

    public void nifCorrecto() {
        jTextField_nif.setEnabled(false);
        jTextField_nombre.setEnabled(true);
        jLabel_nombre.setEnabled(true);
        jTextField_apellidos.setEnabled(true);
        jLabel_apellidos.setEnabled(true);
        jTextField_telefono.setEnabled(true);
        jLabel_telefono.setEnabled(true);
        jTextField_email.setEnabled(true);
        jLabel_email.setEnabled(true);
        jTextField_iban.setEnabled(true);
        jLabel_iban.setEnabled(true);
        jTextField_seguridadsocial.setEnabled(true);
        jLabel_seguridadsocial.setEnabled(true);
        jTextField_calle.setEnabled(true);
        jLabel_calle.setEnabled(true);
        jTextField_numero.setEnabled(true);
        jLabel_numero.setEnabled(true);
        jTextField_otros.setEnabled(true);
        jLabel_otros.setEnabled(true);
        jTextField_codigopostal.setEnabled(true);
        jLabel_codigopostal.setEnabled(true);
        jTextField_localidad.setEnabled(true);
        jLabel_localidad.setEnabled(true);
        jTextField_provincia.setEnabled(true);
        jLabel_provincia.setEnabled(true);
        jPanel_nif.setVisible(false);
        jPanel_aceptardatos.setVisible(true);
    }

    public void datosCorrectos(Empleado emp) {
        jPanel_datos.setVisible(false);
        jPanel_aceptacion.setVisible(true);
        jLabel_nombreyapellidos.setText(emp.getNombre() + " " + emp.getApellidos());
        jLabel_contacto.setText("Tlfno: " + emp.getTelefono() + " | E-mail: " + emp.getEmail());
        Direccion temp = emp.getDireccion();
        jLabel_direccioncompleta.setText("C/" + temp.getCalle() + " Nº" + temp.getNumero() + " " + temp.getOtros());
        jLabel_ibanmostrar.setText("IBAN: " + emp.getIBAN());
        jLabel_seguridadsocialmostrar.setText("Seg. Social: " + emp.getSeguridadSocial());
    }

    public void cancelarCaso() {
        jTextField_nif.setText("");
        jTextField_nif.setEnabled(true);
        jTextField_nombre.setEnabled(false);
        jLabel_nombre.setEnabled(false);
        jTextField_apellidos.setEnabled(false);
        jLabel_apellidos.setEnabled(false);
        jTextField_telefono.setEnabled(false);
        jLabel_telefono.setEnabled(false);
        jTextField_email.setEnabled(false);
        jLabel_email.setEnabled(false);
        jTextField_iban.setEnabled(false);
        jLabel_iban.setEnabled(false);
        jTextField_seguridadsocial.setEnabled(false);
        jLabel_seguridadsocial.setEnabled(false);
        jTextField_calle.setEnabled(false);
        jLabel_calle.setEnabled(false);
        jTextField_numero.setEnabled(false);
        jLabel_numero.setEnabled(false);
        jTextField_otros.setEnabled(false);
        jLabel_otros.setEnabled(false);
        jTextField_codigopostal.setEnabled(false);
        jLabel_codigopostal.setEnabled(false);
        jTextField_localidad.setEnabled(false);
        jLabel_localidad.setEnabled(false);
        jTextField_provincia.setEnabled(false);
        jLabel_provincia.setEnabled(false);
        jPanel_nif.setVisible(true);
        jPanel_aceptardatos.setVisible(false);
        this.cancelarDatos();
    }

    public void cancelarDatos() {
        jTextField_nombre.setText("");
        jTextField_apellidos.setText("");
        jTextField_telefono.setText("");
        jTextField_email.setText("");
        jTextField_iban.setText("");
        jTextField_seguridadsocial.setText("");
        jTextField_calle.setText("");
        jTextField_numero.setText("");
        jTextField_otros.setText("");
        jTextField_codigopostal.setText("");
        jTextField_localidad.setText("");
        jTextField_provincia.setText("");
        jPanel_datos.setVisible(true);
        jPanel_aceptacion.setVisible(false);
        jLabel_nombreyapellidos.setText("temp");
        jLabel_contacto.setText("temp");
        jLabel_direccioncompleta.setText("temp");
        jLabel_ibanmostrar.setText("temp");
        jLabel_seguridadsocialmostrar.setText("temp");
        this.cancelarRolYDestino();
    }

    public void cancelarRolYDestino() {
        jTextField_rol.setText("");
        jTextField_destino.setText("");
    }

    public void errorControlador(String mensaje) {
        JOptionPane.showMessageDialog(new JFrame(), mensaje, "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
    }

    public void mensajeControlador(String mensaje) {
        JOptionPane.showMessageDialog(new JFrame(), mensaje, "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }

    public String getNifValue() {
        return jTextField_nif.getText();
    }

    public String getNombreValue() {
        return jTextField_nombre.getText();
    }

    public String getApellidosValue() {
        return jTextField_apellidos.getText();
    }

    public String getTelefonoValue() {
        return jTextField_telefono.getText();
    }

    public String getEmailValue() {
        return jTextField_email.getText();
    }

    public String getIBANValue() {
        return jTextField_iban.getText();
    }

    public String getSeguridadSocialValue() {
        return jTextField_seguridadsocial.getText();
    }

    public String getCalleValue() {
        return jTextField_calle.getText();
    }

    public String getNumeroValue() {
        return jTextField_numero.getText();
    }

    public String getOtrosValue() {
        return jTextField_otros.getText();
    }

    public String getCodigoPostalValue() {
        return jTextField_codigopostal.getText();
    }

    public String getLocalidadValue() {
        return jTextField_localidad.getText();
    }

    public String getProvinciaValue() {
        return jTextField_provincia.getText();
    }

    public String getRolValue() {
        return jTextField_rol.getText();
    }

    public String getDestinoValue() {
        return jTextField_destino.getText();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptardatos;
    private javax.swing.JButton jButton_aceptarfinal;
    private javax.swing.JButton jButton_cancelarcompleto;
    private javax.swing.JButton jButton_cancelardatos;
    private javax.swing.JButton jButton_cancelarfinal;
    private javax.swing.JButton jButton_nif;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_blue;
    private javax.swing.JLabel jLabel_calle;
    private javax.swing.JLabel jLabel_codigopostal;
    private javax.swing.JLabel jLabel_contacto;
    private javax.swing.JLabel jLabel_datos;
    private javax.swing.JLabel jLabel_destino;
    private javax.swing.JLabel jLabel_direccioncompleta;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_iban;
    private javax.swing.JLabel jLabel_ibanmostrar;
    private javax.swing.JLabel jLabel_localidad;
    private javax.swing.JLabel jLabel_manzana;
    private javax.swing.JLabel jLabel_nif;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_nombreyapellidos;
    private javax.swing.JLabel jLabel_numero;
    private javax.swing.JLabel jLabel_otros;
    private javax.swing.JLabel jLabel_provincia;
    private javax.swing.JLabel jLabel_registro;
    private javax.swing.JLabel jLabel_registroempleado;
    private javax.swing.JLabel jLabel_rol;
    private javax.swing.JLabel jLabel_seguridadsocial;
    private javax.swing.JLabel jLabel_seguridadsocialmostrar;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JPanel jPanel_aceptacion;
    private javax.swing.JPanel jPanel_aceptardatos;
    private javax.swing.JPanel jPanel_botones;
    private javax.swing.JPanel jPanel_datos;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_nif;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator_datos;
    private javax.swing.JTextField jTextField_apellidos;
    private javax.swing.JTextField jTextField_calle;
    private javax.swing.JTextField jTextField_codigopostal;
    private javax.swing.JTextField jTextField_destino;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_iban;
    private javax.swing.JTextField jTextField_localidad;
    private javax.swing.JTextField jTextField_nif;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_numero;
    private javax.swing.JTextField jTextField_otros;
    private javax.swing.JTextField jTextField_provincia;
    private javax.swing.JTextField jTextField_rol;
    private javax.swing.JTextField jTextField_seguridadsocial;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
