/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dis.practicadis.interfaz.vistacontrolador.identificacion;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VistaIdentificacion extends javax.swing.JFrame {

    private ControladorVistaIdentificacion controlador;
    private DefaultListModel modeloLista;
    
    /**
     * Creates new form VistaIdentificacion
     */
    public VistaIdentificacion() {
        modeloLista = new DefaultListModel();
        initComponents();
        controlador = new ControladorVistaIdentificacion(this);
        setResizable(false);
        jPanel_identificacion.setVisible(true);
        jPanel_resultados.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_superior = new javax.swing.JPanel();
        jSeparator = new javax.swing.JSeparator();
        jLabel_manzana = new javax.swing.JLabel();
        jLabel_blue = new javax.swing.JLabel();
        jPanel_inferior = new javax.swing.JPanel();
        jPanel_identificacion = new javax.swing.JPanel();
        jLabel_identificacion = new javax.swing.JLabel();
        jLabel_dni = new javax.swing.JLabel();
        jTextField_dni = new javax.swing.JTextField();
        jLabel_contra = new javax.swing.JLabel();
        jPasswordField_contra = new javax.swing.JPasswordField();
        jButton_aceptar = new javax.swing.JButton();
        jPanel_resultados = new javax.swing.JPanel();
        jLabel_seleccion = new javax.swing.JLabel();
        jButton_aceptarseleccion = new javax.swing.JButton();
        jScrollPane_lista = new javax.swing.JScrollPane();
        jList_lista = new javax.swing.JList<>();
        jButton_cancelarseleccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identificacion");
        setResizable(false);

        jSeparator.setBackground(new java.awt.Color(50, 85, 150));

        jLabel_manzana.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_manzana.setForeground(new java.awt.Color(50, 85, 150));
        jLabel_manzana.setText("Manzana");

        jLabel_blue.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_blue.setForeground(new java.awt.Color(195, 195, 195));
        jLabel_blue.setText("BLUE");

        javax.swing.GroupLayout jPanel_superiorLayout = new javax.swing.GroupLayout(jPanel_superior);
        jPanel_superior.setLayout(jPanel_superiorLayout);
        jPanel_superiorLayout.setHorizontalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_blue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_manzana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_superiorLayout.setVerticalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_blue)
                    .addComponent(jLabel_manzana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_inferior.setLayout(new java.awt.CardLayout());

        jLabel_identificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_identificacion.setText("Identificacion");

        jLabel_dni.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_dni.setText("DNI:");

        jTextField_dni.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jTextField_dni.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_dni.setToolTipText("DNI");
        jTextField_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dniActionPerformed(evt);
            }
        });

        jLabel_contra.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_contra.setText("Contraseña:");

        jPasswordField_contra.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jPasswordField_contra.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField_contra.setToolTipText("Contraseña");
        jPasswordField_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contraActionPerformed(evt);
            }
        });

        jButton_aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_aceptar.setText("Aceptar");
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_identificacionLayout = new javax.swing.GroupLayout(jPanel_identificacion);
        jPanel_identificacion.setLayout(jPanel_identificacionLayout);
        jPanel_identificacionLayout.setHorizontalGroup(
            jPanel_identificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_identificacionLayout.createSequentialGroup()
                .addGroup(jPanel_identificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_identificacionLayout.createSequentialGroup()
                        .addGap(0, 172, Short.MAX_VALUE)
                        .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_identificacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_identificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_identificacion)
                            .addComponent(jLabel_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_dni, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jPasswordField_contra))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_identificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_identificacionLayout.setVerticalGroup(
            jPanel_identificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_identificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_identificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_dni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel_contra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_inferior.add(jPanel_identificacion, "card4");

        jLabel_seleccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_seleccion.setText("Seleccion de tarea");

        jButton_aceptarseleccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_aceptarseleccion.setText("Aceptar");
        jButton_aceptarseleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarseleccionActionPerformed(evt);
            }
        });

        jList_lista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList_lista.setModel(modeloLista);
        jScrollPane_lista.setViewportView(jList_lista);

        jButton_cancelarseleccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_cancelarseleccion.setText("Cancelar");
        jButton_cancelarseleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarseleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_resultadosLayout = new javax.swing.GroupLayout(jPanel_resultados);
        jPanel_resultados.setLayout(jPanel_resultadosLayout);
        jPanel_resultadosLayout.setHorizontalGroup(
            jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_cancelarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_aceptarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                        .addComponent(jLabel_seleccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_resultadosLayout.setVerticalGroup(
            jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_seleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aceptarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_inferior.add(jPanel_resultados, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dniActionPerformed

    private void jPasswordField_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraActionPerformed

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        if(jTextField_dni.getText().isEmpty()){
            errorControlador("El campo DNI esta vacío");
        } else{
            if(String.valueOf(jPasswordField_contra.getPassword()).isEmpty()){
                errorControlador("El campo Contraseña esta vacío");
            } else{
                controlador.procesarEventoIdentificacion();
            }
        }
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_aceptarseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarseleccionActionPerformed
        if(jList_lista.getSelectedValue() == null){
            errorControlador("No hay ningun valor seleccionado seleccionado");
        } else{
            controlador.selectCasoUso();
        }  
    }//GEN-LAST:event_jButton_aceptarseleccionActionPerformed

    private void jButton_cancelarseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarseleccionActionPerformed
        controlador.procesarEventoCancelar();
    }//GEN-LAST:event_jButton_cancelarseleccionActionPerformed

 
    
    public String getUsername() {
        return jTextField_dni.getText();
    }
    public String getPassword() {
        return String.valueOf(jPasswordField_contra.getPassword());
    }
    public String getCasoUso(){
        return jList_lista.getSelectedValue();
    }
    
    public void identificacionCorrecta(ArrayList<String> lista){
        jTextField_dni.setText("");
        jPasswordField_contra.setText("");
        jPanel_identificacion.setVisible(false);
        jPanel_resultados.setVisible(true);
        modeloLista.clear();
        for(int i=lista.size()-1; i>=0; i--){
            modeloLista.addElement(lista.get(i));
        }
    }
    
    public void cancelarCaso(){
        jTextField_dni.setText("");
        jPasswordField_contra.setText("");
        jPanel_identificacion.setVisible(true);
        jPanel_resultados.setVisible(false);
        modeloLista.clear();
    }
    
    public void errorControlador(String mensaje){
        JOptionPane.showMessageDialog(new JFrame(), mensaje, "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        jTextField_dni.setText("");
        jPasswordField_contra.setText("");
    }
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaIdentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaIdentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaIdentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaIdentificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaIdentificacion().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_aceptarseleccion;
    private javax.swing.JButton jButton_cancelarseleccion;
    private javax.swing.JLabel jLabel_blue;
    private javax.swing.JLabel jLabel_contra;
    private javax.swing.JLabel jLabel_dni;
    private javax.swing.JLabel jLabel_identificacion;
    private javax.swing.JLabel jLabel_manzana;
    private javax.swing.JLabel jLabel_seleccion;
    private javax.swing.JList<String> jList_lista;
    private javax.swing.JPanel jPanel_identificacion;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_resultados;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JPasswordField jPasswordField_contra;
    private javax.swing.JScrollPane jScrollPane_lista;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextField jTextField_dni;
    // End of variables declaration//GEN-END:variables
}
