/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dis.practicadis.interfaz.vistacontrolador.comprobardisponibilidad;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class VistaComprobarDisponibilidad extends javax.swing.JFrame {
    private ControladorVistaComprobarDisponibilidad controlador;
    private DefaultListModel modeloListaConExistencias;
    private DefaultListModel modeloListaSinExistencias;

    /**
     * Creates new form VistaDisponibilidad
     */
    public VistaComprobarDisponibilidad() {
        modeloListaConExistencias = new DefaultListModel();
        modeloListaSinExistencias = new DefaultListModel();
        initComponents();
        controlador = new ControladorVistaComprobarDisponibilidad(this);
        setResizable(false);
        jPanel_busqueda.setVisible(true);
        jPanel_resultados.setVisible(false);
        jPanel_tienda.setVisible(false);
        jLabel_pocasexistencias.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_superior = new javax.swing.JPanel();
        jSeparator = new javax.swing.JSeparator();
        jLabel_manzana = new javax.swing.JLabel();
        jLabel_blue = new javax.swing.JLabel();
        jPanel_inferior = new javax.swing.JPanel();
        jPanel_busqueda = new javax.swing.JPanel();
        jTextField_busqueda = new javax.swing.JTextField();
        jLabel_consulta = new javax.swing.JLabel();
        jLabel_producto = new javax.swing.JLabel();
        jButton_aceptar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jPanel_resultados = new javax.swing.JPanel();
        jPanel_productos = new javax.swing.JPanel();
        jLabel_productos = new javax.swing.JLabel();
        jLabel_nombreproducto = new javax.swing.JLabel();
        jLabel_variablenombreproducto = new javax.swing.JLabel();
        jLabel_variableprecioproducto = new javax.swing.JLabel();
        jLabel_precioproducto = new javax.swing.JLabel();
        jLabel_categoriaproducto = new javax.swing.JLabel();
        jLabel_variablecategoriaproducto = new javax.swing.JLabel();
        jPanel_tienda = new javax.swing.JPanel();
        jLabel_tienda = new javax.swing.JLabel();
        jLabel_nombretienda = new javax.swing.JLabel();
        jLabel_telefonotienda = new javax.swing.JLabel();
        jLabel_direcciontienda = new javax.swing.JLabel();
        jLabel_variablenombretienda = new javax.swing.JLabel();
        jLabel_variabletelefonotienda = new javax.swing.JLabel();
        jLabel_variabledirecciontienda = new javax.swing.JLabel();
        jLabel_existenciastienda = new javax.swing.JLabel();
        jLabel_variableexistenciastienda = new javax.swing.JLabel();
        jLabel_pocasexistencias = new javax.swing.JLabel();
        jPanel_conexistencias = new javax.swing.JPanel();
        jLabel_conexistencias = new javax.swing.JLabel();
        jScrollPane_conexistencias = new javax.swing.JScrollPane();
        jList_listacon = new javax.swing.JList<>();
        jPanel_sinexistencias = new javax.swing.JPanel();
        jScrollPane_sinexistencias = new javax.swing.JScrollPane();
        jList_listasin = new javax.swing.JList<>();
        jLabel_sinexistencias = new javax.swing.JLabel();
        jButton_regreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disponibilidad");
        setResizable(false);

        jSeparator.setBackground(new java.awt.Color(50, 85, 150));

        jLabel_manzana.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_manzana.setForeground(new java.awt.Color(50, 85, 150));
        jLabel_manzana.setText("Manzana");

        jLabel_blue.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_blue.setForeground(new java.awt.Color(195, 195, 195));
        jLabel_blue.setText("BLUE");

        javax.swing.GroupLayout jPanel_superiorLayout = new javax.swing.GroupLayout(jPanel_superior);
        jPanel_superior.setLayout(jPanel_superiorLayout);
        jPanel_superiorLayout.setHorizontalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_blue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_manzana)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel_superiorLayout.setVerticalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_blue)
                    .addComponent(jLabel_manzana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_inferior.setLayout(new java.awt.CardLayout());

        jTextField_busqueda.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        jLabel_consulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_consulta.setText("Consulta de disponibilidad:");

        jLabel_producto.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_producto.setText("Producto:");

        jButton_aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_aceptar.setText("Aceptar");
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        jButton_cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_busquedaLayout = new javax.swing.GroupLayout(jPanel_busqueda);
        jPanel_busqueda.setLayout(jPanel_busquedaLayout);
        jPanel_busquedaLayout.setHorizontalGroup(
            jPanel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_producto)
                    .addComponent(jLabel_consulta)
                    .addComponent(jTextField_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_busquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_busquedaLayout.setVerticalGroup(
            jPanel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_consulta)
                .addGap(18, 18, 18)
                .addComponent(jLabel_producto)
                .addGap(18, 18, 18)
                .addComponent(jTextField_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel_inferior.add(jPanel_busqueda, "card2");

        jLabel_productos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_productos.setText("Producto");

        jLabel_nombreproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombreproducto.setText("Nombre");

        jLabel_variablenombreproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variablenombreproducto.setText("temp");

        jLabel_variableprecioproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variableprecioproducto.setText("temp");

        jLabel_precioproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_precioproducto.setText("Precio");

        jLabel_categoriaproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_categoriaproducto.setText("Categoria");

        jLabel_variablecategoriaproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variablecategoriaproducto.setText("temp");

        javax.swing.GroupLayout jPanel_productosLayout = new javax.swing.GroupLayout(jPanel_productos);
        jPanel_productos.setLayout(jPanel_productosLayout);
        jPanel_productosLayout.setHorizontalGroup(
            jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_productosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_productos)
                    .addGroup(jPanel_productosLayout.createSequentialGroup()
                        .addGroup(jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_categoriaproducto)
                            .addComponent(jLabel_precioproducto)
                            .addComponent(jLabel_nombreproducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_variablenombreproducto)
                            .addComponent(jLabel_variablecategoriaproducto)
                            .addComponent(jLabel_variableprecioproducto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_productosLayout.setVerticalGroup(
            jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_productos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombreproducto)
                    .addComponent(jLabel_variablenombreproducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_precioproducto)
                    .addComponent(jLabel_variableprecioproducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_categoriaproducto)
                    .addComponent(jLabel_variablecategoriaproducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_tienda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_tienda.setText("Tienda");

        jLabel_nombretienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombretienda.setText("Nombre");

        jLabel_telefonotienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_telefonotienda.setText("Telefono");

        jLabel_direcciontienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_direcciontienda.setText("Direccion");

        jLabel_variablenombretienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variablenombretienda.setText("temp");

        jLabel_variabletelefonotienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variabletelefonotienda.setText("temp");

        jLabel_variabledirecciontienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variabledirecciontienda.setText("temp");

        jLabel_existenciastienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_existenciastienda.setText("Existencias");

        jLabel_variableexistenciastienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_variableexistenciastienda.setText("temp");

        jLabel_pocasexistencias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_pocasexistencias.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_pocasexistencias.setText("Pocas Existencias");

        javax.swing.GroupLayout jPanel_tiendaLayout = new javax.swing.GroupLayout(jPanel_tienda);
        jPanel_tienda.setLayout(jPanel_tiendaLayout);
        jPanel_tiendaLayout.setHorizontalGroup(
            jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                        .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_direcciontienda)
                            .addComponent(jLabel_nombretienda))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_variablenombretienda)
                            .addComponent(jLabel_variabledirecciontienda))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                        .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel_telefonotienda)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_variabletelefonotienda))
                            .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel_tienda)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_pocasexistencias))
                            .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel_existenciastienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_variableexistenciastienda)))
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        jPanel_tiendaLayout.setVerticalGroup(
            jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tienda)
                    .addComponent(jLabel_pocasexistencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombretienda)
                    .addComponent(jLabel_variablenombretienda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_direcciontienda)
                    .addComponent(jLabel_variabledirecciontienda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_telefonotienda)
                    .addComponent(jLabel_variabletelefonotienda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_existenciastienda)
                    .addComponent(jLabel_variableexistenciastienda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_conexistencias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_conexistencias.setText("Tiendas con existencias:");

        jList_listacon.setModel(modeloListaConExistencias);
        jList_listacon.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_listaconValueChanged(evt);
            }
        });
        jScrollPane_conexistencias.setViewportView(jList_listacon);

        javax.swing.GroupLayout jPanel_conexistenciasLayout = new javax.swing.GroupLayout(jPanel_conexistencias);
        jPanel_conexistencias.setLayout(jPanel_conexistenciasLayout);
        jPanel_conexistenciasLayout.setHorizontalGroup(
            jPanel_conexistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_conexistenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_conexistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_conexistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane_conexistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_conexistenciasLayout.setVerticalGroup(
            jPanel_conexistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_conexistenciasLayout.createSequentialGroup()
                .addComponent(jLabel_conexistencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_conexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList_listasin.setModel(modeloListaSinExistencias);
        jList_listasin.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_listasinValueChanged(evt);
            }
        });
        jScrollPane_sinexistencias.setViewportView(jList_listasin);

        jLabel_sinexistencias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sinexistencias.setText("Tiendas sin existencias:");

        javax.swing.GroupLayout jPanel_sinexistenciasLayout = new javax.swing.GroupLayout(jPanel_sinexistencias);
        jPanel_sinexistencias.setLayout(jPanel_sinexistenciasLayout);
        jPanel_sinexistenciasLayout.setHorizontalGroup(
            jPanel_sinexistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sinexistenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_sinexistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_sinexistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addGroup(jPanel_sinexistenciasLayout.createSequentialGroup()
                        .addComponent(jLabel_sinexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_sinexistenciasLayout.setVerticalGroup(
            jPanel_sinexistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sinexistenciasLayout.createSequentialGroup()
                .addComponent(jLabel_sinexistencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane_sinexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jButton_regreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_regreso.setText("Atrás");
        jButton_regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_regresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_resultadosLayout = new javax.swing.GroupLayout(jPanel_resultados);
        jPanel_resultados.setLayout(jPanel_resultadosLayout);
        jPanel_resultadosLayout.setHorizontalGroup(
            jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_conexistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_regreso)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_sinexistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_tienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_resultadosLayout.setVerticalGroup(
            jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_resultadosLayout.createSequentialGroup()
                .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                        .addComponent(jButton_regreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_resultadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_sinexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_conexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_inferior.add(jPanel_resultados, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        if(jTextField_busqueda.getText().isEmpty()){
            errorControlador("El campo de busqueda esta vacío");
        } else{
            controlador.procesarEventoProducto();
        }
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    private void jButton_regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_regresoActionPerformed
        // TODO add your handling code here:
        controlador.manejarRegreso();
    }//GEN-LAST:event_jButton_regresoActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        controlador.cancelarCaso();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jList_listaconValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_listaconValueChanged
        // TODO add your handling code here:
        jList_listasin.clearSelection();
        controlador.seleccionCon();
    }//GEN-LAST:event_jList_listaconValueChanged

    private void jList_listasinValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_listasinValueChanged
        // TODO add your handling code here:
        jList_listacon.clearSelection();
        controlador.seleccionSin();
    }//GEN-LAST:event_jList_listasinValueChanged

    
    public void productoCorrecto(ArrayList<String> listaConExistencias, ArrayList<String> listaSinExistencias){
        jTextField_busqueda.setText("");
        jPanel_busqueda.setVisible(false);
        jPanel_resultados.setVisible(true);
        jPanel_tienda.setVisible(false);
        modeloListaSinExistencias.clear();
        modeloListaConExistencias.clear();
        for(int i=listaConExistencias.size()-1; i>=0; i--){
            modeloListaConExistencias.addElement(listaConExistencias.get(i));
        }
        for(int i=listaSinExistencias.size()-1; i>=0; i--){
            modeloListaSinExistencias.addElement(listaSinExistencias.get(i));
        }
        jLabel_variablenombreproducto.setText(controlador.getNombreProducto());
        jLabel_variableprecioproducto.setText(controlador.getPrecioProducto()+"€");
        jLabel_variablecategoriaproducto.setText(controlador.getCategoriaProducto());
        jLabel_pocasexistencias.setVisible(false);
        
    }
    
    public void regresoCorrecto(){
        jTextField_busqueda.setText("");
        jPanel_busqueda.setVisible(true);
        jPanel_resultados.setVisible(false);
        jPanel_tienda.setVisible(false);
        modeloListaSinExistencias.clear();
        modeloListaConExistencias.clear();
        jLabel_variablenombreproducto.setText("temp");
        jLabel_variableprecioproducto.setText("temp");
        jLabel_variablecategoriaproducto.setText("temp");
        jLabel_variablenombretienda.setText("temp");
        jLabel_variabledirecciontienda.setText("temp");
        jLabel_variabletelefonotienda.setText("temp");
        jLabel_variableexistenciastienda.setText("temp");
        jLabel_pocasexistencias.setVisible(false);
    }
    
    public void mostrarTienda(){
        jPanel_tienda.setVisible(true);
        if(Integer.parseInt(controlador.getCantidadTienda())<controlador.getPocasUnidades()){
            jLabel_pocasexistencias.setVisible(true);
        } else{
            jLabel_pocasexistencias.setVisible(false);
        }
        jLabel_variablenombretienda.setText(controlador.getNombreTienda());
        jLabel_variabledirecciontienda.setText(controlador.getDireccionTienda());
        jLabel_variabletelefonotienda.setText(controlador.getTelefonoTienda());
        jLabel_variableexistenciastienda.setText(controlador.getCantidadTienda());
    }
    
    public void ocultarTienda(){
        jPanel_tienda.setVisible(false);
        jLabel_variablenombretienda.setText("temp");
        jLabel_variabledirecciontienda.setText("temp");
        jLabel_variabletelefonotienda.setText("temp");
        jLabel_variableexistenciastienda.setText("temp");
        jLabel_pocasexistencias.setVisible(false);
    }
    
    public String getBusqueda() {
        return jTextField_busqueda.getText();
    }
    
    public String getListaConValue(){
        return jList_listacon.getSelectedValue();
    }
    
    public String getListaSinValue(){
        return jList_listasin.getSelectedValue();
    }
    
    public void errorControlador(String mensaje){
        JOptionPane.showMessageDialog(new JFrame(), mensaje, "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        jTextField_busqueda.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaComprobarDisponibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaComprobarDisponibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaComprobarDisponibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaComprobarDisponibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaComprobarDisponibilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_regreso;
    private javax.swing.JLabel jLabel_blue;
    private javax.swing.JLabel jLabel_categoriaproducto;
    private javax.swing.JLabel jLabel_conexistencias;
    private javax.swing.JLabel jLabel_consulta;
    private javax.swing.JLabel jLabel_direcciontienda;
    private javax.swing.JLabel jLabel_existenciastienda;
    private javax.swing.JLabel jLabel_manzana;
    private javax.swing.JLabel jLabel_nombreproducto;
    private javax.swing.JLabel jLabel_nombretienda;
    private javax.swing.JLabel jLabel_pocasexistencias;
    private javax.swing.JLabel jLabel_precioproducto;
    private javax.swing.JLabel jLabel_producto;
    private javax.swing.JLabel jLabel_productos;
    private javax.swing.JLabel jLabel_sinexistencias;
    private javax.swing.JLabel jLabel_telefonotienda;
    private javax.swing.JLabel jLabel_tienda;
    private javax.swing.JLabel jLabel_variablecategoriaproducto;
    private javax.swing.JLabel jLabel_variabledirecciontienda;
    private javax.swing.JLabel jLabel_variableexistenciastienda;
    private javax.swing.JLabel jLabel_variablenombreproducto;
    private javax.swing.JLabel jLabel_variablenombretienda;
    private javax.swing.JLabel jLabel_variableprecioproducto;
    private javax.swing.JLabel jLabel_variabletelefonotienda;
    private javax.swing.JList<String> jList_listacon;
    private javax.swing.JList<String> jList_listasin;
    private javax.swing.JPanel jPanel_busqueda;
    private javax.swing.JPanel jPanel_conexistencias;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_productos;
    private javax.swing.JPanel jPanel_resultados;
    private javax.swing.JPanel jPanel_sinexistencias;
    private javax.swing.JPanel jPanel_superior;
    private javax.swing.JPanel jPanel_tienda;
    private javax.swing.JScrollPane jScrollPane_conexistencias;
    private javax.swing.JScrollPane jScrollPane_sinexistencias;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextField jTextField_busqueda;
    // End of variables declaration//GEN-END:variables
}
