/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dis.practicadis.interfaz.vistacontrolador.selector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class SelectorVista extends javax.swing.JFrame {
    private ControladorSelectorVista controlador;

    /**
     * Creates new form SelectorVista
     */
    public SelectorVista() {
        initComponents();
        controlador = new ControladorSelectorVista(this);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_inferior = new javax.swing.JPanel();
        jButton_caso1 = new javax.swing.JButton();
        jButton_caso2 = new javax.swing.JButton();
        jButton_caso3 = new javax.swing.JButton();
        jButton_caso4 = new javax.swing.JButton();
        jLabel_caso1 = new javax.swing.JLabel();
        jLabel_caso2 = new javax.swing.JLabel();
        jLabel_caso3 = new javax.swing.JLabel();
        jLabel_caso4 = new javax.swing.JLabel();
        jPanel_superior = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_subtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton_caso1.setText("Caso 1");
        jButton_caso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_caso1ActionPerformed(evt);
            }
        });

        jButton_caso2.setText("Caso 2");
        jButton_caso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_caso2ActionPerformed(evt);
            }
        });

        jButton_caso3.setText("Caso 3");
        jButton_caso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_caso3ActionPerformed(evt);
            }
        });

        jButton_caso4.setText("Caso 4");
        jButton_caso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_caso4ActionPerformed(evt);
            }
        });

        jLabel_caso1.setText("Identificarse");

        jLabel_caso2.setText("Consultar disponibilidad de un producto en tiendas físicas");

        jLabel_caso3.setText("Registrar un nuevo empleado");

        jLabel_caso4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_caso4.setText("Recepción en tienda física de un pedido de suministro de producto");

        javax.swing.GroupLayout jPanel_inferiorLayout = new javax.swing.GroupLayout(jPanel_inferior);
        jPanel_inferior.setLayout(jPanel_inferiorLayout);
        jPanel_inferiorLayout.setHorizontalGroup(
            jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_inferiorLayout.createSequentialGroup()
                        .addComponent(jButton_caso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_caso1))
                    .addGroup(jPanel_inferiorLayout.createSequentialGroup()
                        .addComponent(jButton_caso2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_caso2))
                    .addGroup(jPanel_inferiorLayout.createSequentialGroup()
                        .addComponent(jButton_caso3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_caso3))
                    .addGroup(jPanel_inferiorLayout.createSequentialGroup()
                        .addComponent(jButton_caso4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_caso4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_inferiorLayout.setVerticalGroup(
            jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_caso1)
                    .addComponent(jLabel_caso1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_caso2)
                    .addComponent(jLabel_caso2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_caso3)
                    .addComponent(jLabel_caso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_caso4)
                    .addComponent(jLabel_caso4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_titulo.setText("Practica Diseño Software");

        jLabel_subtitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_subtitulo.setText("Selector de caso de uso");

        javax.swing.GroupLayout jPanel_superiorLayout = new javax.swing.GroupLayout(jPanel_superior);
        jPanel_superior.setLayout(jPanel_superiorLayout);
        jPanel_superiorLayout.setHorizontalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_titulo)
                    .addComponent(jLabel_subtitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_superiorLayout.setVerticalGroup(
            jPanel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel_subtitulo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_inferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_caso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_caso1ActionPerformed
        controlador.crearCaso1();
    }//GEN-LAST:event_jButton_caso1ActionPerformed

    private void jButton_caso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_caso2ActionPerformed
        controlador.crearCaso2();
    }//GEN-LAST:event_jButton_caso2ActionPerformed

    private void jButton_caso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_caso3ActionPerformed
        controlador.crearCaso3();
    }//GEN-LAST:event_jButton_caso3ActionPerformed

    private void jButton_caso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_caso4ActionPerformed
        controlador.crearCaso4();
    }//GEN-LAST:event_jButton_caso4ActionPerformed

    
    public void errorControlador(String mensaje){
        JOptionPane.showMessageDialog(new JFrame(), mensaje, "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_caso1;
    private javax.swing.JButton jButton_caso2;
    private javax.swing.JButton jButton_caso3;
    private javax.swing.JButton jButton_caso4;
    private javax.swing.JLabel jLabel_caso1;
    private javax.swing.JLabel jLabel_caso2;
    private javax.swing.JLabel jLabel_caso3;
    private javax.swing.JLabel jLabel_caso4;
    private javax.swing.JLabel jLabel_subtitulo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel_inferior;
    private javax.swing.JPanel jPanel_superior;
    // End of variables declaration//GEN-END:variables
}
